# Generated by Django 3.1.7 on 2021-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0002_auto_20210404_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
