# Generated by Django 3.1.7 on 2021-04-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0004_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='uname',
        ),
    ]
