# Generated by Django 3.1.7 on 2021-04-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0005_auto_20210405_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
