# Generated by Django 3.1.7 on 2021-04-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0006_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='contactNum',
        ),
        migrations.AlterModelTable(
            name='userreg',
            table='usersignup',
        ),
    ]
