# Generated by Django 3.1.7 on 2021-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0008_userreg_contactnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='contactNum',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='uemail',
            field=models.EmailField(max_length=100),
        ),
    ]
