# Generated by Django 3.1.7 on 2021-04-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebsApp', '0009_auto_20210412_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='uemail',
            field=models.CharField(max_length=100),
        ),
    ]
